from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from PyQt5 import *


import SourceFiles.UI.icons.icons_rc as icons_rc
class CustomCard(QWidget):
    def setupUi(self, custom_card):
        if not custom_card.objectName():
            custom_card.setObjectName(u"custom_card")
        custom_card.resize(720, 388)
        self.Card_Frame = QFrame(custom_card)
        self.Card_Frame.setObjectName(u"Card_Frame")
        self.Card_Frame.setGeometry(QRect(9, 69, 509, 216))
        self.Card_Frame.setMinimumSize(QSize(0, 150))
        self.Card_Frame.setMaximumSize(QSize(16777215, 250))
        self.Card_Frame.setStyleSheet(u"background-color: rgb(139, 233, 253);")
        self.horizontalLayout = QHBoxLayout(self.Card_Frame)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.CardImage_Frame = QFrame(self.Card_Frame)
        self.CardImage_Frame.setObjectName(u"CardImage_Frame")
        self.CardImage_Frame.setMinimumSize(QSize(150, 150))
        self.CardImage_Frame.setMaximumSize(QSize(250, 250))
        self.horizontalLayout_2 = QHBoxLayout(self.CardImage_Frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label = QLabel(self.CardImage_Frame)
        self.label.setObjectName(u"label")
        self.label.setStyleSheet(u"border-image: url(:/icons/icons/road.png);\n"
"margin: 10px;")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.CardImage_Frame)
        self.CardContent_Frame = QFrame(self.Card_Frame)
        self.CardContent_Frame.setObjectName(u"CardContent_Frame")
        self.CardContent_Frame.setMinimumSize(QSize(0, 150))
        self.CardContent_Frame.setMaximumSize(QSize(16777215, 250))
        self.verticalLayout = QVBoxLayout(self.CardContent_Frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.CardData_Frame = QFrame(self.CardContent_Frame)
        self.CardData_Frame.setObjectName(u"CardData_Frame")
        self.gridLayout = QGridLayout(self.CardData_Frame)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.Archive_ProjectName = QLabel(self.CardData_Frame)
        self.Archive_ProjectName.setObjectName(u"Archive_ProjectName")
        font = QFont()
        font.setFamily(u"Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Archive_ProjectName.setFont(font)
        self.gridLayout.addWidget(self.Archive_ProjectName, 0, 0, 1, 1, Qt.AlignTop)
        self.Archive_ProjectLength = QLabel(self.CardData_Frame)
        self.Archive_ProjectLength.setObjectName(u"Archive_ProjectLength")
        font1 = QFont()
        font1.setFamily(u"Arial")
        self.Archive_ProjectLength.setFont(font1)
        self.gridLayout.addWidget(self.Archive_ProjectLength, 1, 0, 1, 1, Qt.AlignTop)
        self.Archive_ProjectStatus = QLabel(self.CardData_Frame)
        self.Archive_ProjectStatus.setObjectName(u"Archive_ProjectStatus")
        self.gridLayout.addWidget(self.Archive_ProjectStatus, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.CardData_Frame)
        self.CardButtons_Frame = QFrame(self.CardContent_Frame)
        self.CardButtons_Frame.setObjectName(u"CardButtons_Frame")
        self.horizontalLayout_3 = QHBoxLayout(self.CardButtons_Frame)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.OpenFolder_Button = QPushButton(self.CardButtons_Frame)
        self.OpenFolder_Button.setObjectName(u"OpenFolder_Button")
        self.OpenFolder_Button.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"padding: 5;")
        icon = QIcon()
        icon.addFile(u":/icons/icons/folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.OpenFolder_Button.setIcon(icon)
        self.horizontalLayout_3.addWidget(self.OpenFolder_Button)
        self.OpenAnalyse_Button = QPushButton(self.CardButtons_Frame)
        self.OpenAnalyse_Button.setObjectName(u"OpenAnalyse_Button")
        self.OpenAnalyse_Button.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"padding: 5;")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/file.png", QSize(), QIcon.Normal, QIcon.Off)
        self.OpenAnalyse_Button.setIcon(icon1)
        self.horizontalLayout_3.addWidget(self.OpenAnalyse_Button)
        self.DeleteFolder_Button = QPushButton(self.CardButtons_Frame)
        self.DeleteFolder_Button.setObjectName(u"DeleteFolder_Button")
        self.DeleteFolder_Button.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"padding: 5;")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/trash.png", QSize(), QIcon.Normal, QIcon.Off)
        self.DeleteFolder_Button.setIcon(icon2)
        self.horizontalLayout_3.addWidget(self.DeleteFolder_Button)
        self.verticalLayout.addWidget(self.CardButtons_Frame)
        self.horizontalLayout.addWidget(self.CardContent_Frame)
        self.verticalLayout.addWidget(self.CardButtons_Frame)

        self.retranslateUi(custom_card)

    def retranslateUi(self, custom_card):
        custom_card.setWindowTitle(QCoreApplication.translate("custom_card", u"Form", None))
        self.label.setText(QCoreApplication.translate("custom_card", u"", None))
        self.Archive_ProjectName.setText(QCoreApplication.translate("custom_card", u"Project Name", None))
        self.Archive_ProjectLength.setText(QCoreApplication.translate("custom_card", u"Length", None))
        self.Archive_ProjectStatus.setText(QCoreApplication.translate("custom_card", u"Status", None))
        self.OpenFolder_Button.setText(QCoreApplication.translate("custom_card", u"Open Folder", None))
        self.OpenAnalyse_Button.setText(QCoreApplication.translate("custom_card", u"Open Analyse", None))
        self.DeleteFolder_Button.setText(QCoreApplication.translate("custom_card", u"Delete Project", None))
        QMetaObject.connectSlotsByName(custom_card)
